language: node_js
node_js:
 - "16"
cache:
 directories:
  - node_modules
script:
 - npm test
 - npm run build
before_deploy:
 - npm run build
deploy:
  provider: npm
  email: "$EMAIL"
  api_key: "$API_TOKEN"
  skip_cleanup: true
  on:
    branch: main
notifications:
  email:
  recipients:
    - "$EMAIL"
  on_success: change
  on_failure: always
